name: Hola mundo
on: 
  push: # on push throw
  pull_request: # on pull request throw
  workflow_dispatch: # manual trigger
    inputs:
      name:
        description: 'your name'
        required: true
        default: 'Rolando'
      message:
        description: 'your message'
        required: true
        default: 'Hola mundo from Github Actions!'
jobs: 
  hello:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "Hola ${{ github.event.inputs.name }}! ${{ github.event.inputs.message }}"
  validate:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: download repository
        uses: actions/checkout@v4
      - name: validate readme
        run: test -f README.md
  manual-summary:
    needs: hello
    if: ${{ github.event_name == 'workflow_dispatch' }} 
    runs-on: ubuntu-latest
    steps:
      - name: show summary
        run: echo "The manual execution was completed successfully!"
  pull-request-info:
    needs: validate
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: show pull request info
        env: 
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_TITLE: ${{ github.event.pull_request.title }}

        run: |
          printf 'The pull request was created by %s\n' "$PR_AUTHOR"
          printf 'The pull request title is: %s\n' "$PR_TITLE"