name: Hola mundo
on: 
  push: # on push throw
  workflow_dispatch: # manual trigger
    inputs:
      name:
        description: 'your name'
        required: true
        default: 'Rolando'
      message:
        description: 'your message'
        required: true
        default: 'Hola mundo from Github Actions!'
jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "Hola ${{ github.event.inputs.name }}! ${{ github.event.inputs.message }}"